// Generated by CoffeeScript 1.4.0
var app, assets, auth, express, jsPathify, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

jsPathify = require('connect-assets-jspaths');

auth = require("./auth");

app = express();

app.use(assets());

app.use(express["static"](process.cwd() + "/public"));

app.set('view engine', 'jade');

auth.init(app);

jsPathify(assets, console.log);

app.get(['/', '/about'], function(req, resp) {
  console.log(req.session, resp.session);
  return resp.render('index');
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
