// Generated by CoffeeScript 1.3.3
var mongoose;

mongoose = require("mongoose");

module.exports = {
  ObjectId: mongoose.Schema.ObjectId,
  MakeModelWith: function(name, props) {
    var model, schema;
    schema = new mongoose.Schema(props);
    model = mongoose.model(name, schema);
    return [model, schema];
  }
};
