// Generated by CoffeeScript 1.3.3
var User, goose;

goose = require("./goose");

User = goose.MakeModelWith("User", {
  id: String,
  displayName: String,
  token: String,
  tokenExpire: String
});

module.exports = User;
